---
- name: Refresh apt cache
  tags: apt, cache, always
  hosts: linux
  tasks:
    - name: Refresh apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_pkg_mgr == 'apt'

- name: Install IPA
  tags: ipa, always
  ansible.builtin.import_playbook: 01-ipa.yml

- name: Install Keycloak
  tags: keycloak, always
  ansible.builtin.import_playbook: 02-keycloak.yml

# - name: Deploy Mailcow
#   tags: mailcow, always
#   ansible.builtin.import_playbook: 03-mailcow.yml

...
