---
collections:
  - name: cloud.terraform
    type: git
    source: https://github.com/ansible-collections/cloud.terraform.git
  - name: freeipa.ansible_freeipa
  - name: middleware_automation.keycloak

roles:
  - name: diademiemi.rke2
  - name: diademiemi.docker
  - name: diademiemi.helm

...
