---
collections:
  - name: cloud.terraform
    type: git
    source: https://github.com/diademiemi/cloud.terraform.git  # https://github.com/ansible-collections/cloud.terraform/pull/55

roles:
  - name: diademiemi.k3s
  - name: diademiemi.helm

...
