---
collections:
  - name: cloud.terraform
    type: git
    source: https://github.com/ansible-community/cloud.terraform.git
  - name: theforeman.foreman
  - name: awx.awx

roles:
  - name: diademiemi.rke2
  - name: diademiemi.helm

...
