---

- name: Install K3S
  tags: k3s, always
  ansible.builtin.import_playbook: 01-k3s.yml

- name: Install Kubernetes requisites
  tags: requisites, always
  ansible.builtin.import_playbook: 02-requisites.yml

- name: Deploy AWX
  tags: awx, always
  ansible.builtin.import_playbook: 03-awx.yml

...
