---
all:
  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
  children:
    ipaserver:
      vars:
        ipaadmin_password: "Admin123!"
        ipadm_password: "Admin123!"
        ipaserver_domain: terraform.test
        ipaserver_realm: TERRAFORM.TEST
        ipaserver_setup_dns: true
        ipaserver_auto_forwarders: true
    keycloakserver:
      vars:
        keycloak_quarkus_admin_pass: "AdminAdmin123!"
        keycloak_quarkus_host: "keycloak.terraform.test"
        keycloak_quarkus_frontend_url: "https://keycloak.terraform.test:443/auth"
        keycloak_url: "https://keycloak.terraform.test:443"
        keycloak_quarkus_http_port: 8080
        # keycloak_quarkus_http_port: 80
        # keycloak_quarkus_https_port: 443
        # keycloak_quarkus_https_enabled: true
        keycloak_quarkus_bind_address: 0.0.0.0

...
